# Supabase Configuration File
# Secrets will be injected by GitHub Actions during deployment
# Do NOT put actual values here - use GitHub Repository Secrets instead

# Your 4-digit app passcode (GitHub Secret: APP_PASSCODE)
app_passcode: "${APP_PASSCODE}"

# Supabase Project URL (GitHub Secret: SUPABASE_URL)
supabase_url: "${SUPABASE_URL}"

# Supabase Anon/Public API Key (GitHub Secret: SUPABASE_API_KEY)
supabase_api_key: "${SUPABASE_API_KEY}"

# Optional: Supabase Service Role Key for admin operations (GitHub Secret: SUPABASE_SERVICE_KEY)
# Only use if you need to bypass Row Level Security
supabase_service_key: "${SUPABASE_SERVICE_KEY}"

# List your database tables here
tables:
  - users
  - posts
  - comments
  - products
  - orders
