name: Deploy Supabase CRUD App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create config.js with secrets
      run: |
        cat > config.js << 'EOF'
        window.APP_CONFIG = {
          app_passcode: "${{ secrets.APP_PASSCODE }}",
          supabase_url: "${{ secrets.SUPABASE_URL }}",
          supabase_api_key: "${{ secrets.SUPABASE_API_KEY }}",
          supabase_service_key: "${{ secrets.SUPABASE_SERVICE_KEY }}",
          tables: ["users", "posts", "comments", "products", "orders"]
        };
        EOF
        
        echo "Config file created successfully"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        force_orphan: true
